### ISSUE TITLE
Make an SVG version of the logo

### ISSUE THREAD

**Issue by mlandauer** [mlandauer/thats-camping-elm#86]
It will then be nicely resolution independent and we won't have any issues with colours of green not matching.

**Comment by JoannaHill** [comment]
Thanks boss

**Comment by JoannaHill** [comment]
What is the best version to work off Matthew? I can start this this arvo.

**Comment by mlandauer** [comment]
@JoannaHill The best version to work from is https://github.com/mlandauer/thats-camping-elm/blob/master/src/assets/images/apple-touch-icon.png - believe it or not this is the highest resolution version I have.

**Comment by JoannaHill** [comment]
Could you de-associate my work email? Stuff is coming through on that account.

**Comment by mlandauer** [comment]
Fixed in https://github.com/mlandauer/thats-camping-elm/commit/d16254df524629eb753790ce70a8248a4b4fb6c5. Thank you @JoannaHill!
